### ISSUE TITLE
 file_get_contents(/xxx/vendor/helhum/dotenv-connector/res/PHP/dotenv-include.php): failed to open stream: No such file or directory    on install

### ISSUE THREAD

**Issue by amenk** [helhum/dotenv-connector#1]
Can't install

	composer update
	You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
	Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	  - Installing helhum/dotenv-connector (1.0.0)
	    Loading from cache

		                                                                                                            
	  [ErrorException]                                                                                                  
	  file_get_contents(/xxx/vendor/helhum/dotenv-connector/res/PHP/dotenv-inclu  
	  de.php): failed to open stream: No such file or directory

**Comment by helhum** [comment]
> This development build of composer is over 60 days old

Please update your composer to latest stable release and try again.

If it still happens, please provide the full output of `composer update -vvv` and your root composer.json

**Comment by amenk** [comment]
works, thanks
