### ISSUE TITLE
Environment variables in .env file not substituted when symfony/dotenv is v4.3.6 and upwards

### ISSUE THREAD

**Issue by Abdull** [helhum/dotenv-connector#16]
In my TYPO3 9LTS installation using `helhum/dotenv-connector:v2.1.2` a `.env` file like the following used to work:

```
# assuming `export LINUX_ENVIRONMENT_VARIABLE=okay
MY_VAR=${LINUX_ENVIRONMENT_VARIABLE}
```

Within TYPO3 9LTS, `MY_VAR` would have the value `"okay"`.

This used to work with transitive dependency `symfony/dotenv` up until and including `v4.3.5`. But with `symfony/dotenv:v4.3.6` and upwards, `MY_VAR` is empty.

Can anyone else reproduce this problem?

**Comment by helhum** [comment]
@Abdull I cannot confirm your observation.

My test scenario:

composer.json:
```json
{
    "require": {
        "helhum/dotenv-connector": "^2.1"
    }
}
```

.env:
```bash
FOO=${BAR}
```

test.php:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
var_dump(getenv('FOO'));
```


```bash
export BAR=export
php test.php
# string(6) "export"
BAR=override php test.php
# string(8) "override"
```

So the case you describe works for me. Anything else I could test? Can you try my test scenario as well?

**Comment by Abdull** [comment]
Here is my upstream discussion to this bug: https://github.com/symfony/symfony/issues/34598#issuecomment-559812555

**Comment by helhum** [comment]
@Abdull Thanks a bunch for posting such elaborate description of the issue to the upstream repo! I’ll keep this open for a while and will decide whether I need to switch to a different dotenv parsing lib in the end. But I guess there will be a solution/ fix for upstream.

**Comment by Abdull** [comment]
The symfony-Maintainers fixed this issue, see https://github.com/symfony/symfony/issues/34598 .

E.g., https://github.com/symfony/dotenv/tree/v4.4.2 does no longer have the reported issue.

So from my side, _this_ dotenv-connector issue can be closed.

**Comment by helhum** [comment]
> The symfony-Maintainers fixed this issue

@Abdull Cool! Thanks for reporting this back!
