### ISSUE TITLE
New version throws RuntimeException after composer update

### ISSUE THREAD

**Issue by tpinne** [helhum/dotenv-connector#22]
I ran `composer update` just now and and this lib has been updated from 2.1.2 to the new version 2.2.0.

I immediately get the exception of the new feature
```
[RuntimeException]
Include file template defined for helhum/dotenv-connector does not exist!
```

with the following part of my `composer.json` untouched

```
	"extra": {
		"helhum/dotenv-connector": {
			"env-file": ".env"
		}
	}
```

After a second run of `composer update` there is no exception and the following message is included in the output:
```
helhum/dotenv-connector: Generated dotenv include file
```

After that the project runs normal.

**Comment by helhum** [comment]
Thanks for the report! That is indeed unfortunate. I's really a pain to provide Composer plugins that flawlessly work during plugin upgrades :-/

**Comment by helhum** [comment]
@tpinne 2.2.1 should fix this. can you confirm?

**Comment by tpinne** [comment]
I try to find another project where an upgrade from 2.1.x would be applied tomorrow to recreate the same steps.
