### ISSUE TITLE
Symfony Dependencies vs. composer 2 support

### ISSUE THREAD

**Issue by bmack** [helhum/dotenv-connector#29]
Hey,

thanks for this great package, I use it in all my TYPO3 installations.

However, I wanted to introduce your dotenv connector with TYPO3 v7 + composer2 now.

Here's my problem currently:
* dotenv-connector v3 supports Symfony5 only and composer1+2
* dotenv-connector v2 supports Symfony3+4 only and composer1

Would it be possible to either
a) support Symfony3/4 in dotenv connector 3 ?
b) or support composer 2 in dotenv connector 2?

If you are open for it, I could also try to come up with a PR. Whatever your preference would be...?

**Comment by helhum** [comment]
Thanks Benni. 

a pull requests that brings Composer 2 support to V2 would be great!

**Comment by helhum** [comment]
@bmack created a 2.x branch for your PR just now

**Comment by helhum** [comment]
Hm @bmack as far as I can see 2.3.1 [supports composer 2](https://packagist.org/packages/helhum/dotenv-connector#v2.3.1) so what exactly is the issue you are running into?

**Comment by helhum** [comment]
Used 2.3.1 in a project with Composer 2 just fine right now. Will close this.
@bmack In case you have further feedback, just drop a line here anyway.

**Comment by bmack** [comment]
FYI for everybody else: It wasn't a dotenv-connector issue but related to another composer plugin.
