### ISSUE TITLE
How to set realurl domains

### ISSUE THREAD

**Issue by simonschaufi** [helhum/dotenv-connector#3]
This is more of an "best practise" issue, not a bug.

At the moment I'm setting my domains with this snippet in realurl_config.php
```php
foreach ([
	'domain1.de' => 1,
	'domain2.de' => 17,
	'dev.domain1.de' => 1,
	'dev.domain2.de' => 17,
	'staging.domain1.de' => 1,
	'staging.domain2.de' => 17
] as $key => $value) {
	$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$key] = $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'];
	$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$key]['pagePath']['rootpage_id'] = $value;
	$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['www.' . $key] = $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$key];
}
```
I'm thinking about doing this with .env but have no idea how I could solve that. Any idea?

I'm also not really sure how those 2 lines should work:

https://github.com/helhum/TYPO3-Distribution/blob/master/.env-example#L24-L25

**Comment by helhum** [comment]
See https://github.com/helhum/TYPO3-Distribution for a suggestion.

It uses config loader to set values from .env as TYPO3_CONF_VARS:
https://github.com/helhum/TYPO3-Distribution/blob/master/.env-example#L24-L25

Reference these values in your realurl config:

```php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'][$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['site_configuration']['realurl_domain']] = $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT'];
```
