### ISSUE TITLE
Latest Release v3.0.0 requires PHP 7.2.5 but seems not really to be required mandatory?!

### ISSUE THREAD

**Issue by typoworx-de** [helhum/dotenv-connector#30]
I'm running PHP 7.2.34 and for some reason I got the v3.0.0 installed via composer. But now every time composer complains about Symfony-Components yielding for PHP 7.2.5.

So far the DotEnv was running fine - except these CLI issues for Composer. Is this a mandatory requirement or just a nice-to-have feature using the most recent HTTP-Foundation components in v.3.0.0 release?

**Comment by helhum** [comment]
Hey @typoworx-de 
Thanks for trying out my software. To be able to help with your issues, I kindly ask you to provide:

1. A clear description of the steps you are doing
2. A clear decription of your expectations
3. A clear decription of the acutal result, at best with exact messages or error messages you are seeing.

For what I understand, you seem to have issues with Composer error messages.

Regarding dependencies: The dependencies of this package are correct and [decleared correctly](https://github.com/helhum/dotenv-connector/blob/dcfd35a103c722b473c51829dd909ff6b3b69829/composer.json#L21-L25)

So there is nothing really I can change here.
