### ISSUE TITLE
TYPO3-related: .env not loading / broken?

### ISSUE THREAD

**Issue by iammati** [helhum/dotenv-connector#34]
Got the following situation whenever my coworker's .env file contains the following line
`CORE_EXT=site_core`
it kinda breaks the connection to the database (see attached screenshot)
![image](https://user-images.githubusercontent.com/41418763/124977631-fe093380-e030-11eb-98de-c1838a26fcad.png)

removing that line makes it look like the db connection works fine but the custom extension throws an exception because it depends on that value.

I have a ddev environment and cannot reproduce the issue at all. I have the value `CORE_EXT` inside my own .env file and it works fine - no exception at all.

The only difference we both have is that I'm using an AdditionalConfiguration.php file generated by ddev (for the db credentials) while my coworker uses this:
![image](https://user-images.githubusercontent.com/41418763/124978277-d8c8f500-e031-11eb-8146-f77991ac383e.png)

I'm not sure if the keys are right at all since I wasn't able to find a documentation or anything similiar.
I hope somebody can help here

PHP version: 7.4.19
helhum/dotenv-connector version: 3.0.0
TYPO3: 10.4.17

**Comment by helhum** [comment]
Honestly, this is indeed a TYPO3 related question and has nothing to do with this package. In fact it not even is a TYPO3 related question, but an issue you have with your individual setup and/or configuration.

Since I don't know anything about the latter, I can't help, sorry. 

I'd suggest you search for CORE_EXT in your project files to find out where exactly this env var is evaluated.

**Comment by iammati** [comment]
@helhum I mean I know it is more likely an individual issue but I didn't mention that even after removing the custom extension (and also the CORE_EXT-thingy) it still threw the exception

**Comment by iammati** [comment]
Also it'd be really helpful to know what the proper setup looks like in the .env file for the DB credentials or in general, haven't found anything yet honestly

**Comment by helhum** [comment]
Feel free to ask on [TYPO3 Slack](https://typo3.org/community/meet/chat-slack/) or [Stackoverflow](https://stackoverflow.com/questions/tagged/typo3)
