### ISSUE TITLE
update from symfony/dotenv v5.3.0 to v5.3.4 breaks setup

### ISSUE THREAD

**Issue by Geddo** [helhum/dotenv-connector#36]
In symfony/dotenv v5.3.4 the function str_starts_with() is beeing used wich returns an fatal error in my setup:
`PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Dotenv\str_starts_with() in /var/www/html/vendor/symfony/dotenv/Dotenv.php:193
Stack trace:
#0 /var/www/html/vendor/symfony/dotenv/Dotenv.php(568): Symfony\Component\Dotenv\Dotenv->populate(Array, false)
#1 /var/www/html/vendor/symfony/dotenv/Dotenv.php(92): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#2 /var/www/html/vendor/helhum/dotenv-connector/src/Adapter/SymfonyDotEnv.php(15): Symfony\Component\Dotenv\Dotenv->load('/var/www/html/....')
#3 /var/www/html/vendor/helhum/dotenv-include.php(4): Helhum\DotEnvConnector\Adapter\SymfonyDotEnv->exposeToEnvironment('/var/www/html/....')
#4 /var/www/html/vendor/helhum/dotenv-include.php(5): Helhum\DotEnvConnector\IncludeFile::{closure}('/var/www/html/....')
#5 /var/www/html/vendor/helhum/dotenv-connector/src/IncludeFile.php(65): require('/var/www/html/v...')
#6 /var/www/html/vendor/helhum/dotenv-connector/src/Plugin.php(99): Helhum\DotEnvConnector\IncludeFile->dump()
#7 [internal function]: Helhu in /var/www/html/vendor/symfony/dotenv/Dotenv.php on line 193`

**Comment by Geddo** [comment]
This seems releated: https://github.com/symfony/symfony/issues/42280 (thanks to Christian Fries for the hint)

**Comment by helhum** [comment]
Not sure if I can do much here. Waiting for SF and Composer folks to respond.
Otherwise I might consider doing what I always strove to avoid and that is forking a Dotenv parser code and delivering it with this small tool.

**Comment by christian-fries** [comment]
In the meantime, we can use symfony/dotenv 5.3.0 or 4.4.25

**Comment by helhum** [comment]
Introduced with symfony/dotenv v5.3.4, v5.2.12, v4.4.27

**Comment by Geddo** [comment]
I guess they will revert the changes so this will be fixed with the next update I guess. In the meanwhile we can conflict v5.3.0
So, this issue is more an information for helhum/dotenv-connector-users than a actually bug report ;-)

**Comment by pulponair** [comment]
> Not sure if I can do much here. Waiting for SF and Composer folks to respond.
> Otherwise I might consider doing what I always strove to avoid and that is forking a Dotenv parser code and delivering it with this small tool.

Well can't you just run the dotenv-include at a later state when polyfills are already available?

**Comment by helhum** [comment]
I won't add conflicts this time

**Comment by helhum** [comment]
> > Not sure if I can do much here. Waiting for SF and Composer folks to respond.
> > Otherwise I might consider doing what I always strove to avoid and that is forking a Dotenv parser code and delivering it with this small tool.
> 
> Well can't you just run the dotenv-include at a later state when polyfills are already available?

nope

**Comment by helhum** [comment]
Might be fixed in SF upstream, therefore will close here
