### ISSUE TITLE
Question about TYPO3 V 13

### ISSUE THREAD

**Issue by conpassione** [helhum/dotenv-connector#46]
I have to setups, one for TYPO3 13 and one for TYPO3 11
In both i have a .env File with a option `TEST='Test'`

In my settings.yaml File for both Setups i wrote: `cp-test: '%env(TEST)%'`

In my pagetemplate.typoscript in both setups i use the Setting from my settings.yamel like this: 
`page.10.variables.cp-test=TEXT`
`page.10.variables.cp-test.value={$cp-test}`

In the corresponding Fluid-Templates i use the variable:
`<p>Das ist ein Test: {cp-test}</p>`

The resulting FE-Output:
V11 as expected: "Das ist ein Test: Test"
V13 not as expected: "Das ist ein Test: %evn(TEST)%"

I use the newest Version von deotenv-connector, TYPO3 13 and PHP 8.2

How would it be possible to have in V13 the same FE-Output as ub V11? Am i doing somthing wrong? Or is it a Bug? 

Thanks for any adwise.

Best Regards
Renzo

**Comment by helhum** [comment]
This package here is independent from any application or version it is used for. it exposes env vars from a .env file to php. 

for that it uses symfony/dotenv

there are now two options:

* symfony changed something
* typo3 changed something

@conpassione can you change 

TYPO3_CONTEXT to Development in v13 using the .env file?

**Comment by conpassione** [comment]
Yes, no Problem.
I did some more investigations and found that dotenv-connector is working fine. I see all the entries in .env when i get dem by typoscript. Given in .env File: 
`TEST='Test`
i can get this variable in typoscript (as variables entry for my FLUIDTEMPLATE):
`mytest := getEnv(TEST)`
In the FE Output in a Fluid template i can write:
`{mytest}`
And the Result is as expexted "Test"

So i think, that while reading a yaml File TYPO3 does not translate the entry `%env()%` correct. So the Error is in TYPO3.
1000 Thanks to You for this cool Extension.

**Comment by conpassione** [comment]
As the Problem is in TYPO3 and not in dotenv-connector, i close this Issue.

**Comment by helhum** [comment]
Thank you very much for your feedback and further testing!
