### ISSUE TITLE
Cannot update from v1.1.0 to v2.0.2

### ISSUE THREAD

**Issue by stucki** [helhum/dotenv-connector#5]
The update fails with the following error:

```
  [ErrorException]                                                                                                                      
  file_get_contents(/app/vendor/helhum/dotenv-connector/res/PHP/dotenv-include.tmpl): failed to open stream: No such file or directory  
```

If I re-run `composer install`, then it's fine. However, I don't like to break the deployment process.

The problem seems to happen because the old version 1 code is loaded (and executed) during `composer install`. Version 1 needs to have this file, but version 2 does not ship it any more...

Have you got any idea how I can skip the error?

**Comment by helhum** [comment]
I‘m sorry, but there is no mitigation to this as version 1 has a plugin that works improperly on upgrade but it’s code is beeing executed on upgrade. version 2 has code to avoid this for future upgrades

**Comment by stucki** [comment]
Thanks for your feedback.

**Comment by stucki** [comment]
Here is how I catched this:

- when `composer show` reports that the package is at version 1
- and `composer.lock` reports that it should update to version 2
- then create an empty file `vendor/helhum/dotenv-connector/res/PHP/dotenv-include.tmpl`

In case this helps anyone:

```
diff --git a/composer.json b/composer.json
index 5e3a514..c59ec62 100644
--- a/composer.json
+++ b/composer.json
@@ -90,6 +90,9 @@
         "post-update-cmd": [
             "@typo3-update-schema"
         ],
+        "post-package-update": [
+            "OLDVERSION=$(composer show | grep \"helhum/dotenv-connector\" | awk '{print $2}'); NEWVERSION=$(grep -A 1 \"helhum/dotenv-connector\" composer.lock | grep \"version\" | awk -F\\\" '{print $4}' | grep \"^2\"); if echo $OLDVERSION | grep -q \"^1\" && echo $NEWVERSION | grep -q \"^2\" && test -d vendor/helhum/dotenv-connector/; then touch vendor/helhum/dotenv-connector/res/PHP/dotenv-include.tmpl; fi"
+        ],
         "typo3-update-schema": [
             "bin/typo3cms database:updateschema \"*.add,*.change\""
         ],
```

**Comment by helhum** [comment]
Cool, thanks!
